### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by XhmikosR**
Switch to `https` for JS files to avoid mixed content.

Also, convert tabs to spaces while at it.

### CODE REVIEW

**Comment by tarcieri** [comment]
Haha, none of those scripts are even necessary. They're just kind of junking up the page.

Perhaps the site should be redone in Bootstrap 4 or something...

**Comment by XhmikosR** [comment]
True that but I'd wait for v4 a little more. Maybe do it with 3.x which is
pretty much the same syntax wise.

Note that jQuery is needed for transitions for the mobile menu.

**Comment by XhmikosR** [comment]
Correction for the collapse plugin.

**Comment by digitalextremist** [comment]
@XhmikosR it's usually better to omit the schema, and whatever was used to make the request will be used to load the scripts. So rather than `https://url` it could just be `//url`

**Comment by XhmikosR** [comment]
I'll just lol at the lesson :p

The choice for this change was made on purpose.

**Pull request merged**
