### PR TITLE
Rebuild Celluloid Website

### PR DESCRIPTION
**Pull request by wisn**
You may see the demo on http://www.nurcahyo.me/celluloid.github.com/

I didn't use any CSS framework because a tiny CSS + NormalizeCSS is enough.
The website quite responsive. The document size should be only 205 Kb.
I think it's a bad idea using `https://github.com/celluloid/*/raw/master/logo.png` for the logo.
Should we take the logo to the Celluloid Website repository?

Feel free to ask me everything~

### CODE REVIEW

**Comment by tarcieri** [comment]
Continuing the discussion from #7:

* I think there's way too much gray... maybe ditch it all and go for a mostly-white page?
* Overall it could benefit from more color. The previous site used blue as an accent color. I don't have my heart set on blue, but I think it could benefit from at least one more color, especially on the buttons
* Round the corners on the buttons
* The navigation tabs look "boxy". I'd suggest losing the boxes and using color and font weight to differentiate the active tab
* Perhaps lose the box entirely on the navigation bar and have the page elements free-floating against a white background
* I dislike the centered text. I'd suggest left-justifying it as in the original site
* The "Another Projects" and "Links" text seem out-of-place, unnecessary, and distracting. I'd suggest getting rid of it
* I'm not a fan of the dashed underlines on the links

**Comment by wisn** [comment]
Alright, work on it~
Did you like to use CC-Atrribution licensed template like [HTML5Up](https://html5up.net/)?

**Comment by tarcieri** [comment]
Yes that's fine

**Comment by wisn** [comment]
Please tell me the name of template that you love from HTML5Up...

**Comment by tarcieri** [comment]
I was suggesting some tweaks you can do to your existing design rather than using a template. I don't particularly like any of those templates and would suggest something white an minimalist.

**Comment by wisn** [comment]
Okay, work on it~

**Comment by wisn** [comment]
@tarcieri
You may now check it out on https://www.nurcahyo.me/celluloid.github.com/ for the demo~

**Comment by tarcieri** [comment]
That's a big improvement, thanks! Merged

**Pull request merged**
